# Generated by Django 5.1 on 2024-08-25 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='facebook_Id_link',
            field=models.URLField(blank=True, max_length=255, validators=[django.core.validators.URLValidator()]),
        ),
    ]
