# Generated by Django 5.0.6 on 2024-08-30 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_facebook_id_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='facebook_Id_link',
            field=models.URLField(blank=True, default=None, max_length=255, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(default=None, upload_to='client/images/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_no',
            field=models.CharField(default=None, max_length=12),
        ),
    ]
