# Generated by Django 5.0.6 on 2024-08-30 08:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_facebook_id_link_alter_client_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='facebook_Id_link',
            field=models.URLField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='client/images/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
