# Generated by Django 5.1 on 2024-08-25 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('createad', models.DateTimeField(auto_now_add=True)),
                ('rating', models.CharField(choices=[('✩', '✩'), ('✩✩', '✩✩'), ('✩✩✩', '✩✩✩'), ('✩✩✩✩', '✩✩✩✩'), ('✩✩✩✩✩', '✩✩✩✩✩')], max_length=10)),
                ('slug', models.SlugField(max_length=40)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
        ),
    ]
