# Generated by Django 5.1 on 2024-08-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('✩', 'one'), ('✩✩', 'two'), ('✩✩✩', 'three'), ('✩✩✩✩', 'four'), ('✩✩✩✩✩', 'five')], max_length=10),
        ),
    ]
