# Generated by Django 5.0.6 on 2024-08-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_remove_review_reviewer_remove_review_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='review',
        ),
        migrations.AddField(
            model_name='service',
            name='review',
            field=models.ManyToManyField(to='service.review'),
        ),
    ]
