# Generated by Django 5.0.6 on 2024-08-26 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_facebook_id_link'),
        ('service', '0006_remove_service_review_service_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='createad',
            new_name='created_on',
        ),
        migrations.RemoveField(
            model_name='service',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AddField(
            model_name='review',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.service'),
            preserve_default=False,
        ),
    ]
