# Generated by Django 5.1 on 2024-08-25 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='order_type',
            new_name='order_status',
        ),
    ]
